- name: Prepare host for AWX
  hosts: all
  become: true
  gather_facts: true

  vars:
    awx_user: awx_user
    zabbix_hostname: "{{ ansible_fqdn }}"
    zabbix_agent_listen_port: 10050
    zabbix_version: "7.4"

  tasks:
    - name: Set system hostname
      hostname:
        name: "{{ inventory_hostname }}"

    - name: Ensure Python 3 is installed
      package:
        name: python3
        state: present

    - name: Configure User and Groups
      user:
        name: "{{ awx_user }}"
        shell: /bin/bash
        create_home: yes
        # Maps 'sudo' for Debian/Ubuntu and 'wheel' for RHEL/Alma
        groups: "{{ 'sudo' if ansible_os_family == 'Debian' else 'wheel' }}"
        append: yes

    - name: Allow passwordless sudo
      copy:
        dest: "/etc/sudoers.d/{{ awx_user }}"
        content: "{{ awx_user }} ALL=(ALL) NOPASSWD:ALL"
        mode: "0440"

    - name: Install basic packages
      package:
        name: [git, curl, wget, open-vm-tools]
        state: present

    #######################################################
    # Zabbix Installation (Dynamic Repo Detection)
    #######################################################

    - name: Install Zabbix repository (Debian Family)
      block:
        - name: Download and install Zabbix .deb
          apt:
            deb: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/release/debian/pool/main/z/zabbix-release/zabbix-release_latest_{{ zabbix_version }}+debian{{ ansible_distribution_major_version }}_all.deb"
            state: present
      when: ansible_os_family == "Debian"

    - name: Install Zabbix repository (RedHat Family)
      block:
        - name: Install Zabbix .rpm
          dnf:
            name: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/release/alma/{{ ansible_distribution_major_version }}/noarch/zabbix-release-latest-{{ zabbix_version }}.el{{ ansible_distribution_major_version }}.noarch.rpm"
            state: present
            disable_gpg_check: yes
      when: ansible_os_family == "RedHat"

    - name: Install Zabbix Agent 2
      package:
        name: zabbix-agent2
        state: present
        update_cache: yes

    - name: Configure Zabbix Agent 2
      copy:
        dest: /etc/zabbix/zabbix_agent2.conf
        content: |
          Server={{ zabbix_server }}
          ServerActive={{ zabbix_server }}
          Hostname={{ zabbix_hostname }}
          ListenPort={{ zabbix_agent_listen_port }}
          HostMetadata=autoreg_linux
        owner: root
        group: root
        mode: '0644'
      notify: Restart Zabbix agent 2

    - name: Start Zabbix Agent
      service:
        name: zabbix-agent2
        state: started
        enabled: true

  handlers:
    - name: Restart Zabbix agent 2
      service:
        name: zabbix-agent2
        state: restarted
