---
- name: Test fact gathering for AWX
  hosts: all
  gather_facts: yes
  become: true

  tasks:
    - name: Ensure we can connect
      ping:

    - name: Show inventory info
      debug:
        msg: "inventory_hostname={{ inventory_hostname }}, ansible_host={{ ansible_host }}"

    - name: Collect all facts using setup module
      setup:

    - name: Show OS info fact
      debug:
        var: ansible_facts['os_family']

    - name: Show CPU count fact
      debug:
        var: ansible_facts['processor_cores']
