- name: Gather host facts and set custom facts
  hosts: all
  gather_facts: yes
  become: true

  tasks:
    - name: Set custom AWX fact
      set_fact:
        custom_awx_info:
          bootstrapped_user: awx_user
          public_key_added: true
